osx_image: xcode7.3
language: objective-c
script:
  xctool
  -workspace MHScrollingHeader.xcworkspace
  -scheme MHScrollingHeader
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
branches:
  only:
    master
